######################################################################
# This file was autogenerated by 'configure'. Do not edit it directly!
# Invocation was: ./antigen/configure 
######################################################################
WITH_LOCK=yes
WITH_DEFER=yes
WITH_CACHE=yes
WITH_DEBUG=yes
WITH_PARALLEL=yes
WITH_EXTENSIONS=yes
WITH_COMPLETION=yes
######################################################################
